### ISSUE TITLE
Sonata Admin not populating fields with content

### ISSUE THREAD

**Issue by jrdnrc** [a2lix/TranslationFormBundle#140]
Hi,
I'm using the TranslationFormBundle along with the i18n Doctrine bundle, and I'm having an issue in that after I create/edit an entity within Sonata Admin, the Sonata Admin fields are not populated with the translations.

![Sonata admin form](https://cloud.githubusercontent.com/assets/1749312/3316454/e3ea5458-f702-11e3-9fc5-1a5c48f9a59b.png)
(Product code is not translatable)

However, I can see that the translations are being saved in the database:
![Database 1](https://cloud.githubusercontent.com/assets/1749312/3316473/0223cc9c-f703-11e3-8f9c-37c079645398.png)
![Database 2](https://cloud.githubusercontent.com/assets/1749312/3316474/03f6c66e-f703-11e3-8b0e-b35cd6f878c4.png)

My form config:

``` php
protected function configureFormFields(FormMapper $form)  
{  
    $form  
        ->add('translations', 'a2lix_translations')  
        ->add('code');  
}
```

Product entity XML: http://pastebin.com/mEpS4S4w
Product entity PHP: http://pastebin.com/AeRLkAcZ

Product translation XML: http://pastebin.com/WqQv1PY5
Product translation PHP: http://pastebin.com/PBqk0vdp

i18n Config:

``` yml
a2lix_i18n_doctrine:
    manager_registry: doctrine

doctrine:
    orm:
        entity_managers:
            default:
                filters:
                    oneLocale:
                        class: A2lix\I18nDoctrineBundle\Doctrine\ORM\Filter\OneLocaleFilter
                        enabled: true
```

Translation config:

``` yml
a2lix_translation_form:
    locales: [fr, es, de, en]       # [1]
    required_locales: en
    manager_registry: doctrine      # [3]
    templating: "A2lixTranslationFormBundle::default.html.twig"      # [4]
```

Any help would be appreciated. Thanks
