### ISSUE TITLE
Constraints on form fields even if locale is not required and empty

### ISSUE THREAD

**Issue by NV-iloweb** [a2lix/TranslationFormBundle#172]
Example : 
config.yml
```
a2lix_translation_form:
    locales: [fr,en]
    required_locales: [fr]
    manager_registry: doctrine
    templating: "AcmeBundle::translation.html.twig"
```

FormType
```
$builder
            ->add('translations', 'a2lix_translations', array(
                'fields' => array(
                    'content' => array(
                        'label' => 'lorem.ipsum',
                        'required' => true,
                        'constraints' => array(
                            new NotBlank()
                        )
                    )
                )
            ));
```
If I submit this form without anything in the "en" it will still check the constraint on it since only the datas are removed at the Submit event.
A possible solution could be listening to the preSubmit event and checking for each locale if the viewData is not empty and if so, removing the form for this locale + datas. I haven't finished testing this solution yet.
