### ISSUE TITLE
How can I use custom locale provider?

### ISSUE THREAD

**Issue by karmazzin** [a2lix/TranslationFormBundle#239]
I'm trying to create custom local provider. I've wrote:
(just for test)
```
<?php
namespace SmartKid\AdminBundle\Locale;

use A2lix\TranslationFormBundle\Locale;
use Symfony\Component\DependencyInjection\ContainerInterface;

class DatabaseProvider extends Locale\DefaultProvider implements Locale\LocaleProviderInterface {

}
```
register service
```
...
    locale_doctrine_provider:
        class: SmartKid\AdminBundle\Locale\DatabaseProvider
....
```

and changed     locale_provider config name to own service.
```
a2lix_translation_form:
    locale_provider: locale_doctrine_provider       # [1]
    locales: [ru, fr, es, de]          # [1-a]
    default_locale: ru             # [1-b]
    required_locales: [ru]         # [1-c]
    manager_registry: doctrine      # [2]
    templating: "A2lixTranslationFormBundle::default.html.twig"      # [3]
```

But I got only:
```
 [ERROR] Built-in server terminated unexpectedly.                                                                       
```
Without any info. 
It possible someone have working example of custom locale_provider?
cc @webda2l, @gonzalovilaseca maybe you can help me?
