### ISSUE TITLE
Bug when using default_locale different than symfony default locale

### ISSUE THREAD

**Issue by skonsoft** [a2lix/TranslationFormBundle#5]
i set in my config.yml:

```
#a2lix/translation-form-bundle
a2lix_translation_form:
    default_locale: tfng                  # [Optionnal] Default to 'en'
    locales: [fr, ar]               # [Optionnal] Array of translations locales. Can be specified in the form. 
    default_required: false             # [Optionnal] Default to false. In this case, translation fields are not mark as required with html5
```

and my default symfony locale is _fr_

i wanted to translate _label_ property of entity Dictionnary, and the logic is to have label in main entity written in _tifinagh_.

When i use your bundle, i got a problem of duplicate foreign key (fr). but when i changed the defaut locale to fr, it works nice.

```
ix/translation-form-bundle
a2lix_translation_form:
    default_locale: fr                  # [Optionnal] Default to 'en'
    locales: [en, ar]               # [Optionnal] Array of translations locales. Can be specified in the form. 
    default_required: false             # [Optionnal] Default to false. In this case, translation fields are not mark as required with html5
```

thanks to fix yhis bug: Dont save the default_locale in Translation entity, when it's a property in the main Enitity.
