### ISSUE TITLE
Required languages

### ISSUE THREAD

**Issue by pdias** [a2lix/TranslationFormBundle#99]
If I'm not wrong, all languages ​​will be required...

In config:

```
a2lix_translation_form:
    locales: [en, pt, fr]
    default_required: true
    manager_registry: doctrine
    templating: "A2lixTranslationFormBundle::default.html.twig"
```

This **`default_required: true`** will do all languages required, not only the default language.

My opinion is to make this `default_required: true` in a array with the required locales, for example like this **`locales_required: [en, fr]`**.

I do not know if it will be the best idea ...

Thanks,

Paulo
